"""
@Author = 'Michael Stanley'

============ Change Log ============
2025-Jan-03 = Created. 

============ License ============
Copyright (C) 2025 Michael Stanley

This file is part of wmul_rivendell.

wmul_rivendell is free software: you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the Free 
Software Foundation, either version 3 of the License, or (at your option) any 
later version.

wmul_rivendell is distributed in the hope that it will be useful, but WITHOUT 
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with 
wmul_rivendell. If not, see <https://www.gnu.org/licenses/>. 
"""
from pathlib import Path

from wmul_rivendell.LoadCartDataDump import RivendellCart, CartType
from wmul_rivendell.DatabaseStatistics import DatabaseStatistics, StatisticsLimits


def test__organize_by_rivendell_group():
    defined_carts = [
        RivendellCart(cart_number='3000', cut_number='1', type=CartType.Audio, group_name='PRO_30', title='Dingo Mick', artist='WMUL-FM', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: PRO/0000', conductor='', song_id='', user_defined='', description='Dingo Mick', outcue='', filename='003000_001.wav', length=':29', start_point='0', end_point='29648', segue_start_point='-1', segue_end_point='-1', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='0', fadeup_point='-1', fadedown_point='-1', sched_codes=''),
        RivendellCart(cart_number='3001', cut_number='1', type=CartType.Audio, group_name='PRO_30', title='I Want My WMUL', artist='WMUL-FM', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: PRO/0003', conductor='', song_id='', user_defined='', description='I Want My WMUL', outcue='', filename='003001_001.wav', length=':29', start_point='0', end_point='29413', segue_start_point='-1', segue_end_point='-1', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='0', fadeup_point='-1', fadedown_point='-1', sched_codes=''),
        RivendellCart(cart_number='3002', cut_number='1', type=CartType.Audio, group_name='PRO_30', title='Dull Day', artist='WMUL-FM', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: PRO/0004', conductor='', song_id='', user_defined='', description='Dull Day', outcue='', filename='003002_001.wav', length=':30', start_point='0', end_point='30014', segue_start_point='29988', segue_end_point='29988', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='0', fadeup_point='-1', fadedown_point='-1', sched_codes=''),
        RivendellCart(cart_number='3003', cut_number='1', type=CartType.Audio, group_name='PRO_30', title='Use the Force', artist='WMUL-FM', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: PRO/0005', conductor='', song_id='', user_defined='', description='Use the Force', outcue='', filename='003003_001.wav', length=':29', start_point='0', end_point='29805', segue_start_point='-1', segue_end_point='-1', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='0', fadeup_point='-1', fadedown_point='-1', sched_codes=''),
        RivendellCart(cart_number='3004', cut_number='1', type=CartType.Audio, group_name='PRO_30', title='News Recruitment', artist='WMUL-FM News', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: PRO/0006', conductor='', song_id='', user_defined='', description='News Recruitment', outcue='', filename='003004_001.wav', length=':31', start_point='0', end_point='31007', segue_start_point='30981', segue_end_point='30981', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='0', fadeup_point='-1', fadedown_point='-1', sched_codes=''),
        RivendellCart(cart_number='3005', cut_number='1', type=CartType.Audio, group_name='PRO_30', title='Are You High?', artist='WMUL-FM', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: PRO/0011', conductor='', song_id='', user_defined='', description='Are You High?', outcue='', filename='003005_001.wav', length=':29', start_point='0', end_point='29518', segue_start_point='-1', segue_end_point='-1', hook_start_point='-1', hook_end_point='-1', talk_start_point='-1', talk_end_point='-1', fadeup_point='-1', fadedown_point='-1', sched_codes=''),
        RivendellCart(cart_number='3006', cut_number='1', type=CartType.Audio, group_name='PRO_30', title='News On The Way Home', artist='WMUL-FM News', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: PRO/0014', conductor='', song_id='', user_defined='', description='News On The Way Home', outcue='', filename='003006_001.wav', length=':29', start_point='0', end_point='29883', segue_start_point='-1', segue_end_point='-1', hook_start_point='-1', hook_end_point='-1', talk_start_point='-1', talk_end_point='-1', fadeup_point='-1', fadedown_point='-1', sched_codes=''),
        RivendellCart(cart_number='3007', cut_number='1', type=CartType.Audio, group_name='PRO_30', title='Stuff You Want', artist='WMUL-FM', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: PRO/0017', conductor='', song_id='', user_defined='', description='Stuff You Want', outcue='', filename='003007_001.wav', length=':29', start_point='0', end_point='29831', segue_start_point='-1', segue_end_point='-1', hook_start_point='-1', hook_end_point='-1', talk_start_point='-1', talk_end_point='-1', fadeup_point='-1', fadedown_point='-1', sched_codes=''),
        RivendellCart(cart_number='3008', cut_number='1', type=CartType.Audio, group_name='PRO_30', title='Too Sexy', artist='WMUL-FM', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: PRO/0018', conductor='', song_id='', user_defined='', description='Too Sexy', outcue='', filename='003008_001.wav', length=':30', start_point='0', end_point='30380', segue_start_point='-1', segue_end_point='-1', hook_start_point='-1', hook_end_point='-1', talk_start_point='-1', talk_end_point='-1', fadeup_point='-1', fadedown_point='-1', sched_codes=''),
        RivendellCart(cart_number='3009', cut_number='1', type=CartType.Audio, group_name='PRO_30', title='Worldwide Leader 1', artist='WMUL-FM Sports', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: PRO/0020', conductor='', song_id='', user_defined='', description='Worldwide Leader 1', outcue='', filename='003009_001.wav', length=':29', start_point='0', end_point='29962', segue_start_point='-1', segue_end_point='-1', hook_start_point='-1', hook_end_point='-1', talk_start_point='-1', talk_end_point='-1', fadeup_point='-1', fadedown_point='-1', sched_codes=''),
        RivendellCart(cart_number='3300', cut_number='1', type=CartType.Audio, group_name='PRO_60', title='Alternative', artist='WMUL-FM Music Formats', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: PRO/0084', conductor='', song_id='', user_defined='', description='Alternative', outcue='', filename='003300_001.wav', length='1:00', start_point='0', end_point='60003', segue_start_point='-1', segue_end_point='-1', hook_start_point='-1', hook_end_point='-1', talk_start_point='-1', talk_end_point='-1', fadeup_point='-1', fadedown_point='-1', sched_codes=''),
        RivendellCart(cart_number='3301', cut_number='1', type=CartType.Audio, group_name='PRO_60', title='Blues', artist='WMUL-FM Music Formats', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: PRO/0085', conductor='', song_id='', user_defined='', description='Blues', outcue='', filename='003301_001.wav', length=':59', start_point='0', end_point='59924', segue_start_point='-1', segue_end_point='-1', hook_start_point='-1', hook_end_point='-1', talk_start_point='-1', talk_end_point='-1', fadeup_point='-1', fadedown_point='-1', sched_codes=''),
        RivendellCart(cart_number='3302', cut_number='1', type=CartType.Audio, group_name='PRO_60', title='DJ Shaft', artist='WMUL-FM', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: PRO/0001', conductor='', song_id='', user_defined='', description='DJ Shaft', outcue='', filename='003302_001.wav', length='1:00', start_point='0', end_point='60603', segue_start_point='-1', segue_end_point='-1', hook_start_point='-1', hook_end_point='-1', talk_start_point='-1', talk_end_point='-1', fadeup_point='-1', fadedown_point='-1', sched_codes=''),
        RivendellCart(cart_number='3303', cut_number='1', type=CartType.Audio, group_name='PRO_60', title='Sports Leader 13', artist='Nick Verozlini ', album='', year='', isrc='', isci='', label='', client='Nick Verozlini', agency='', publisher='', composer='', conductor='', song_id='', user_defined='', description='"sports leader 13.wav"', outcue='', filename='003303_001.wav', length='1:00', start_point='0', end_point='60188', segue_start_point='-1', segue_end_point='-1', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='0', fadeup_point='-1', fadedown_point='-1', sched_codes=''),
        RivendellCart(cart_number='3304', cut_number='1', type=CartType.Audio, group_name='PRO_60', title='Jazz', artist='WMUL-FM Music Formats', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: PRO/0087', conductor='', song_id='', user_defined='', description='Jazz', outcue='', filename='003304_001.wav', length='1:00', start_point='0', end_point='60029', segue_start_point='-1', segue_end_point='-1', hook_start_point='-1', hook_end_point='-1', talk_start_point='-1', talk_end_point='-1', fadeup_point='-1', fadedown_point='-1', sched_codes=''),
        RivendellCart(cart_number='3305', cut_number='1', type=CartType.Audio, group_name='PRO_60', title='Marshall Championship Moments', artist='WMUL-FM Sports', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: PRO/1000', conductor='', song_id='', user_defined='', description='Marshall Championship Moments', outcue='', filename='003305_001.wav', length='1:00', start_point='0', end_point='60003', segue_start_point='-1', segue_end_point='-1', hook_start_point='-1', hook_end_point='-1', talk_start_point='-1', talk_end_point='-1', fadeup_point='-1', fadedown_point='-1', sched_codes=''),
        RivendellCart(cart_number='3306', cut_number='1', type=CartType.Audio, group_name='PRO_60', title='Out Of This World', artist='WMUL-FM', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: PRO/0007', conductor='', song_id='', user_defined='', description='Out Of This World', outcue='', filename='003306_001.wav', length='1:00', start_point='0', end_point='60003', segue_start_point='-1', segue_end_point='-1', hook_start_point='-1', hook_end_point='-1', talk_start_point='-1', talk_end_point='-1', fadeup_point='-1', fadedown_point='-1', sched_codes=''),
        RivendellCart(cart_number='3307', cut_number='1', type=CartType.Audio, group_name='PRO_60', title='Pre-Game Show', artist='WMUL-FM Sports', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: PRO/1012', conductor='', song_id='', user_defined='', description='Pre-Game Show', outcue='', filename='003307_001.wav', length='1:00', start_point='0', end_point='60081', segue_start_point='-1', segue_end_point='-1', hook_start_point='-1', hook_end_point='-1', talk_start_point='-1', talk_end_point='-1', fadeup_point='-1', fadedown_point='-1', sched_codes=''),
        RivendellCart(cart_number='3308', cut_number='1', type=CartType.Audio, group_name='PRO_60', title='Rain or Shine', artist='WMUL-FM Sports', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: PRO/1010', conductor='', song_id='', user_defined='', description='Rain or Shine', outcue='', filename='003308_001.wav', length=':59', start_point='0', end_point='59846', segue_start_point='-1', segue_end_point='-1', hook_start_point='-1', hook_end_point='-1', talk_start_point='-1', talk_end_point='-1', fadeup_point='-1', fadedown_point='-1', sched_codes=''),
        RivendellCart(cart_number='3310', cut_number='1', type=CartType.Audio, group_name='PRO_60', title='Sports Leader 10', artist='WMUL-FM Sports', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: PRO/0079', conductor='', song_id='', user_defined='', description='Sports Leader 10', outcue='', filename='003310_001.wav', length='1:00', start_point='0', end_point='60003', segue_start_point='-1', segue_end_point='-1', hook_start_point='-1', hook_end_point='-1', talk_start_point='-1', talk_end_point='-1', fadeup_point='-1', fadedown_point='-1', sched_codes=''),
        RivendellCart(cart_number='100000', cut_number='1', type=CartType.Audio, group_name='ALTERNATIV', title="There's a Star", artist='Ash', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: A00/0001', conductor='', song_id='', user_defined='', description="There's a Star", outcue='', filename='100000_001.wav', length='4:22', start_point='0', end_point='262000', segue_start_point='260000', segue_end_point='262000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='10000', fadeup_point='-1', fadedown_point='-1', sched_codes='2000s|Flashback'),
        RivendellCart(cart_number='100001', cut_number='1', type=CartType.Audio, group_name='ALTERNATIV', title='Six Feet Under', artist='No Doubt', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: A00/0002', conductor='', song_id='', user_defined='', description='Six Feet Under', outcue='', filename='100001_001.wav', length='2:28', start_point='0', end_point='148000', segue_start_point='146000', segue_end_point='148000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='6000', fadeup_point='-1', fadedown_point='-1', sched_codes='2000s|Flashback'),
        RivendellCart(cart_number='100002', cut_number='1', type=CartType.Audio, group_name='ALTERNATIV', title='Portions for Foxes', artist='Rilo Kiley', album='', year='2004', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: A00/0003', conductor='', song_id='', user_defined='', description='Portions for Foxes', outcue='', filename='100002_001.wav', length='4:43', start_point='0', end_point='283000', segue_start_point='280000', segue_end_point='283000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='34000', fadeup_point='-1', fadedown_point='-1', sched_codes='2000s'),
        RivendellCart(cart_number='100003', cut_number='1', type=CartType.Audio, group_name='ALTERNATIV', title='Maybe Tomorrow', artist='Stereophonics', album='', year='2004', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: A00/0004', conductor='', song_id='', user_defined='', description='Maybe Tomorrow', outcue='', filename='100003_001.wav', length='4:35', start_point='0', end_point='275000', segue_start_point='271000', segue_end_point='275000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='30000', fadeup_point='-1', fadedown_point='-1', sched_codes='2000s|Flashback'),
        RivendellCart(cart_number='100004', cut_number='1', type=CartType.Audio, group_name='ALTERNATIV', title='Existentialism on Prom Night', artist='Straylight Run', album='', year='2004', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: A00/0005', conductor='', song_id='', user_defined='', description='Existentialism on Prom Night', outcue='', filename='100004_001.wav', length='3:59', start_point='0', end_point='239000', segue_start_point='234000', segue_end_point='239000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='28000', fadeup_point='-1', fadedown_point='-1', sched_codes='2000s|Flashback'),
        RivendellCart(cart_number='100005', cut_number='1', type=CartType.Audio, group_name='ALTERNATIV', title='Your Ex-Lover is Dead', artist='Stars', album='', year='2004', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: A00/0006', conductor='', song_id='', user_defined='', description='Your Ex-Lover is Dead', outcue='', filename='100005_001.wav', length='4:13', start_point='0', end_point='253000', segue_start_point='251000', segue_end_point='253000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='0', fadeup_point='-1', fadedown_point='-1', sched_codes='2000s|Flashback'),
        RivendellCart(cart_number='100006', cut_number='1', type=CartType.Audio, group_name='ALTERNATIV', title='Neighborhood #1 (Tunnels)', artist='Arcade Fire', album='', year='2004', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: A00/0007', conductor='', song_id='', user_defined='', description='Neighborhood #1 (Tunnels)', outcue='', filename='100006_001.wav', length='4:47', start_point='0', end_point='287000', segue_start_point='285000', segue_end_point='287000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='25000', fadeup_point='-1', fadedown_point='-1', sched_codes='2000s|Flashback'),
        RivendellCart(cart_number='100007', cut_number='1', type=CartType.Audio, group_name='ALTERNATIV', title='How to Disappear Completely', artist='Radiohead', album='', year='2000', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: A00/0008', conductor='', song_id='', user_defined='', description='How to Disappear Completely', outcue='', filename='100007_001.wav', length='5:53', start_point='0', end_point='353000', segue_start_point='351000', segue_end_point='353000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='41000', fadeup_point='-1', fadedown_point='-1', sched_codes='2000s|Flashback'),
        RivendellCart(cart_number='100008', cut_number='1', type=CartType.Audio, group_name='ALTERNATIV', title='Pin', artist='Yeah Yeah Yeahs', album='', year='2003', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: A00/0009', conductor='', song_id='', user_defined='', description='Pin', outcue='', filename='100008_001.wav', length='1:59', start_point='0', end_point='119000', segue_start_point='117000', segue_end_point='119000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='22000', fadeup_point='-1', fadedown_point='-1', sched_codes='2000s|Flashback'),
        RivendellCart(cart_number='100009', cut_number='1', type=CartType.Audio, group_name='ALTERNATIV', title='Juxtapozed with U', artist='Super Furry Animals', album='', year='2001', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: A00/0010', conductor='', song_id='', user_defined='', description='Juxtapozed with U', outcue='', filename='100009_001.wav', length='3:09', start_point='0', end_point='189000', segue_start_point='188000', segue_end_point='189000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='25000', fadeup_point='-1', fadedown_point='-1', sched_codes='2000s|Flashback'),
        RivendellCart(cart_number='100010', cut_number='1', type=CartType.Audio, group_name='ALTERNATIV', title='New Slang', artist='The Shins', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: A00/0011', conductor='', song_id='', user_defined='', description='New Slang', outcue='', filename='100010_001.wav', length='3:45', start_point='0', end_point='225000', segue_start_point='221000', segue_end_point='225000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='36000', fadeup_point='-1', fadedown_point='-1', sched_codes='2000s|Flashback'),
        RivendellCart(cart_number='100011', cut_number='1', type=CartType.Audio, group_name='ALTERNATIV', title='War on War', artist='Wilco', album='', year='2002', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: A00/0012', conductor='', song_id='', user_defined='', description='War on War', outcue='', filename='100011_001.wav', length='3:49', start_point='0', end_point='229000', segue_start_point='227000', segue_end_point='229000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='50000', fadeup_point='-1', fadedown_point='-1', sched_codes='2000s|Flashback'),
        RivendellCart(cart_number='100012', cut_number='1', type=CartType.Audio, group_name='ALTERNATIV', title='Drift Away', artist='Uncle Kracker', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: A00/0013', conductor='', song_id='', user_defined='', description='Drift Away', outcue='', filename='100012_001.wav', length='4:13', start_point='0', end_point='253000', segue_start_point='246000', segue_end_point='253000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='12000', fadeup_point='-1', fadedown_point='-1', sched_codes='2000s|Flashback'),
        RivendellCart(cart_number='100013', cut_number='1', type=CartType.Audio, group_name='ALTERNATIV', title='Neighborhood #2 (Laika)', artist='Arcade Fire', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: A00/0014', conductor='', song_id='', user_defined='', description='Neighborhood #2 (Laika)', outcue='', filename='100013_001.wav', length='3:27', start_point='0', end_point='207000', segue_start_point='205000', segue_end_point='207000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='23000', fadeup_point='-1', fadedown_point='-1', sched_codes='2000s|Flashback'),
        RivendellCart(cart_number='100014', cut_number='1', type=CartType.Audio, group_name='ALTERNATIV', title='Neighborhood #3 (Power Out)', artist='Arcade Fire', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: A00/0015', conductor='', song_id='', user_defined='', description='Neighborhood #3 (Power Out)', outcue='', filename='100014_001.wav', length='5:08', start_point='0', end_point='308000', segue_start_point='308000', segue_end_point='308000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='15000', fadeup_point='-1', fadedown_point='-1', sched_codes='2000s|Flashback'),
        RivendellCart(cart_number='100015', cut_number='1', type=CartType.Audio, group_name='ALTERNATIV', title='Neighborhood #4 (7 Kettles)', artist='Arcade Fire', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: A00/0016', conductor='', song_id='', user_defined='', description='Neighborhood #4 (7 Kettles)', outcue='', filename='100015_001.wav', length='4:40', start_point='0', end_point='280000', segue_start_point='272000', segue_end_point='280000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='22000', fadeup_point='-1', fadedown_point='-1', sched_codes='2000s|Flashback'),
        RivendellCart(cart_number='100016', cut_number='1', type=CartType.Audio, group_name='ALTERNATIV', title='5/4', artist='Gorillaz', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: A00/0017', conductor='', song_id='', user_defined='', description='5/4', outcue='', filename='100016_001.wav', length='2:39', start_point='0', end_point='159000', segue_start_point='156000', segue_end_point='159000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='12000', fadeup_point='-1', fadedown_point='-1', sched_codes='2000s|Flashback'),
        RivendellCart(cart_number='100017', cut_number='1', type=CartType.Audio, group_name='ALTERNATIV', title='Cute Without the E', artist='Taking Back Sunday', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: A00/0018', conductor='', song_id='', user_defined='', description='Cute Without the E', outcue='', filename='100017_001.wav', length='3:31', start_point='0', end_point='211000', segue_start_point='207000', segue_end_point='211000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='5000', fadeup_point='-1', fadedown_point='-1', sched_codes='2000s|Flashback'),
        RivendellCart(cart_number='100018', cut_number='1', type=CartType.Audio, group_name='ALTERNATIV', title='Pinch Me', artist='Barenaked Ladies', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: A00/0019', conductor='', song_id='', user_defined='', description='Pinch Me', outcue='', filename='100018_001.wav', length='4:37', start_point='0', end_point='277000', segue_start_point='270000', segue_end_point='277000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='13000', fadeup_point='-1', fadedown_point='-1', sched_codes='2000s|Flashback'),
        RivendellCart(cart_number='100019', cut_number='1', type=CartType.Audio, group_name='ALTERNATIV', title='Move Your Feet', artist='Junior Senior', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: A00/0020', conductor='', song_id='', user_defined='', description='Move Your Feet', outcue='', filename='100019_001.wav', length='3:02', start_point='0', end_point='182000', segue_start_point='180000', segue_end_point='182000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='6000', fadeup_point='-1', fadedown_point='-1', sched_codes='2000s|Flashback'),
        RivendellCart(cart_number='150000', cut_number='1', type=CartType.Audio, group_name='STREETBEAT', title='Dig It', artist='D-Tent Boys', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: H00/0001', conductor='', song_id='', user_defined='', description='Dig It', outcue='', filename='150000_001.wav', length='3:42', start_point='0', end_point='222000', segue_start_point='222000', segue_end_point='222000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='0', fadeup_point='-1', fadedown_point='-1', sched_codes='2000s|Flashback'),
        RivendellCart(cart_number='150001', cut_number='1', type=CartType.Audio, group_name='STREETBEAT', title='The New Workout Plan', artist='Kanye West', album='', year='2004', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: H00/0002', conductor='', song_id='', user_defined='2004', description='The New Workout Plan', outcue='', filename='150001_001.wav', length='5:23', start_point='0', end_point='323000', segue_start_point='323000', segue_end_point='323000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='0', fadeup_point='-1', fadedown_point='-1', sched_codes='2000s|Flashback'),
        RivendellCart(cart_number='150002', cut_number='1', type=CartType.Audio, group_name='STREETBEAT', title='One Beer', artist='MF Doom', album='', year='2004', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: H00/0003', conductor='', song_id='', user_defined='2004', description='One Beer', outcue='', filename='150002_001.wav', length='4:18', start_point='0', end_point='258000', segue_start_point='258000', segue_end_point='258000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='0', fadeup_point='-1', fadedown_point='-1', sched_codes='2000s|Flashback'),
        RivendellCart(cart_number='150003', cut_number='1', type=CartType.Audio, group_name='STREETBEAT', title='Rhyme or Reason', artist='Eminem', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: H10/0001', conductor='', song_id='', user_defined='', description='Rhyme or Reason', outcue='', filename='150003_001.wav', length='5:04', start_point='0', end_point='304715', segue_start_point='304715', segue_end_point='304715', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='8000', fadeup_point='-1', fadedown_point='-1', sched_codes='2010s'),
        RivendellCart(cart_number='150004', cut_number='1', type=CartType.Audio, group_name='STREETBEAT', title='Banana Clipper (feat. Big Boi)', artist='Run the Jewels', album='', year='2013', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: H10/0002', conductor='', song_id='', user_defined='2013', description='Banana Clipper (feat. Big Boi)', outcue='', filename='150004_001.wav', length='2:51', start_point='0', end_point='171000', segue_start_point='171000', segue_end_point='171000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='4000', fadeup_point='-1', fadedown_point='-1', sched_codes='2010s'),
        RivendellCart(cart_number='150005', cut_number='1', type=CartType.Audio, group_name='STREETBEAT', title='Diamonds Dancing', artist='Drake & Future', album='', year='2015', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: H15/0001', conductor='', song_id='', user_defined='2015', description='Diamonds Dancing', outcue='', filename='150005_001.wav', length='5:02', start_point='0', end_point='302000', segue_start_point='302000', segue_end_point='302000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='15000', fadeup_point='-1', fadedown_point='-1', sched_codes='2015s'),
        RivendellCart(cart_number='150006', cut_number='1', type=CartType.Audio, group_name='STREETBEAT', title="Chillin' (Ice Cold)", artist='Griemes', album='', year='2017', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: H17/0002', conductor='', song_id='', user_defined='', description="Chillin' (Ice Cold)", outcue='', filename='150006_001.wav', length='3:40', start_point='0', end_point='220000', segue_start_point='215000', segue_end_point='220000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='23000', fadeup_point='-1', fadedown_point='-1', sched_codes='2015s'),
        RivendellCart(cart_number='150007', cut_number='1', type=CartType.Audio, group_name='STREETBEAT', title='Boop Bop Da Willy Willy', artist='Griemes', album='', year='2017', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: H17/0003', conductor='', song_id='', user_defined='', description='Boop Bop Da Willy Willy', outcue='', filename='150007_001.wav', length='3:53', start_point='0', end_point='233000', segue_start_point='231000', segue_end_point='233000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='16000', fadeup_point='-1', fadedown_point='-1', sched_codes='2015s'),
        RivendellCart(cart_number='150008', cut_number='1', type=CartType.Audio, group_name='STREETBEAT', title='Make You Mine', artist='Stoop', album='', year='2017', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: H17/0004', conductor='', song_id='', user_defined='', description='Make You Mine', outcue='', filename='150008_001.wav', length='3:40', start_point='0', end_point='220000', segue_start_point='220000', segue_end_point='220000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='17000', fadeup_point='-1', fadedown_point='-1', sched_codes='2015s'),
        RivendellCart(cart_number='150009', cut_number='1', type=CartType.Audio, group_name='STREETBEAT', title='XXX (feat. U2)', artist='Kendrick Lamar', album='', year='2017', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: H17/0005', conductor='', song_id='', user_defined='', description='XXX (feat. U2)', outcue='', filename='150009_001.wav', length='4:13', start_point='0', end_point='253000', segue_start_point='252000', segue_end_point='253000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='5000', fadeup_point='-1', fadedown_point='-1', sched_codes='2015s'),
        RivendellCart(cart_number='150010', cut_number='1', type=CartType.Audio, group_name='STREETBEAT', title='Taboo (Vinyl)', artist='Denzel Curry', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: H18/0001', conductor='', song_id='', user_defined='', description='Taboo (Vinyl)', outcue='', filename='150010_001.wav', length='3:16', start_point='0', end_point='196000', segue_start_point='196000', segue_end_point='196000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='40000', fadeup_point='-1', fadedown_point='-1', sched_codes=''),
        RivendellCart(cart_number='150011', cut_number='1', type=CartType.Audio, group_name='STREETBEAT', title='Taboo', artist='Denzel Curry', album='', year='2018', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: H18/0001', conductor='', song_id='', user_defined='', description='Taboo', outcue='', filename='150011_001.wav', length='3:16', start_point='0', end_point='196000', segue_start_point='196000', segue_end_point='196000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='40000', fadeup_point='-1', fadedown_point='-1', sched_codes='2015s|Vinyl'),
        RivendellCart(cart_number='150012', cut_number='1', type=CartType.Audio, group_name='STREETBEAT', title='Let the Speakers Blow', artist='Big Gigantic', album='', year='2020', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: H20/0001', conductor='', song_id='', user_defined='', description='Let the Speakers Blow', outcue='', filename='150012_001.wav', length='3:12', start_point='0', end_point='192000', segue_start_point='190000', segue_end_point='192000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='0', fadeup_point='-1', fadedown_point='-1', sched_codes='2020'),
        RivendellCart(cart_number='150013', cut_number='1', type=CartType.Audio, group_name='STREETBEAT', title='Free Your Mind (feat. Jennifer Hartswick)', artist='Big Gigantic', album='', year='2020', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: H20/0002', conductor='', song_id='', user_defined='', description='Free Your Mind (feat. Jennifer Hartswick)', outcue='', filename='150013_001.wav', length='4:15', start_point='0', end_point='255000', segue_start_point='250000', segue_end_point='255000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='0', fadeup_point='-1', fadedown_point='-1', sched_codes='2020'),
        RivendellCart(cart_number='150014', cut_number='1', type=CartType.Audio, group_name='STREETBEAT', title='Friends (feat. Ashe)', artist='Big Gigantic', album='', year='2020', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: H20/0003', conductor='', song_id='', user_defined='', description='Friends (feat. Ashe)', outcue='', filename='150014_001.wav', length='3:55', start_point='0', end_point='235000', segue_start_point='233000', segue_end_point='235000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='9000', fadeup_point='-1', fadedown_point='-1', sched_codes='2020'),
        RivendellCart(cart_number='150015', cut_number='1', type=CartType.Audio, group_name='STREETBEAT', title='Let the Music Heal Me (feat. Tiago Vasquez)', artist='Dubgee', album='', year='2020', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: H20/0004', conductor='', song_id='', user_defined='', description='Let the Music Heal Me (feat. Tiago Vasquez)', outcue='', filename='150015_001.wav', length='3:15', start_point='0', end_point='195000', segue_start_point='195000', segue_end_point='195000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='17000', fadeup_point='-1', fadedown_point='-1', sched_codes='2020'),
        RivendellCart(cart_number='150016', cut_number='1', type=CartType.Audio, group_name='STREETBEAT', title='Maria', artist='Dubgee', album='', year='2020', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: H20/0005', conductor='', song_id='', user_defined='', description='Maria', outcue='', filename='150016_001.wav', length='3:51', start_point='0', end_point='231000', segue_start_point='230000', segue_end_point='231000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='5000', fadeup_point='-1', fadedown_point='-1', sched_codes='2020'),
        RivendellCart(cart_number='150017', cut_number='1', type=CartType.Audio, group_name='STREETBEAT', title='Not Enough', artist='Dubgee', album='', year='2020', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: H20/0006', conductor='', song_id='', user_defined='', description='Not Enough', outcue='', filename='150017_001.wav', length='2:40', start_point='0', end_point='160000', segue_start_point='159000', segue_end_point='160000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='0', fadeup_point='-1', fadedown_point='-1', sched_codes='2020'),
        RivendellCart(cart_number='150018', cut_number='1', type=CartType.Audio, group_name='STREETBEAT', title='Car Thief', artist='Beastie Boys', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: H80/0001', conductor='', song_id='', user_defined='', description='Car Thief', outcue='', filename='150018_001.wav', length='3:39', start_point='0', end_point='219000', segue_start_point='210000', segue_end_point='219000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='21000', fadeup_point='-1', fadedown_point='-1', sched_codes='1980s|Flashback'),
        RivendellCart(cart_number='150019', cut_number='1', type=CartType.Audio, group_name='STREETBEAT', title='Shake Your Rump', artist='Beastie Boys', album='', year='', isrc='', isci='', label='', client='', agency='', publisher='', composer='Imported from WOAFR: H80/0002', conductor='', song_id='', user_defined='', description='Shake Your Rump', outcue='', filename='150019_001.wav', length='3:19', start_point='0', end_point='199000', segue_start_point='198000', segue_end_point='199000', hook_start_point='-1', hook_end_point='-1', talk_start_point='0', talk_end_point='1000', fadeup_point='-1', fadedown_point='-1', sched_codes='1980s|Flashback'),
    ]

    mock_rivendell_carts = "mock_rivendell_carts"
    mock_filename = "mock_filename"

    stats_limits = StatisticsLimits()

    ds = DatabaseStatistics(
        rivendell_carts=mock_rivendell_carts, 
        output_filename=mock_filename, 
        stats_limits=stats_limits
    )

    organized_carts = ds._organize_by_rivendell_group(defined_carts)

    assert len(organized_carts.keys()) == 4
    
    PRO_30_carts = organized_carts["PRO_30"]
    assert len(PRO_30_carts) == 10

    PRO_60_carts = organized_carts["PRO_60"]
    assert len(PRO_60_carts) == 10

    ALTERNATIV_carts = organized_carts["ALTERNATIV"]
    assert len(ALTERNATIV_carts) == 20

    STREETBEAT_carts = organized_carts["STREETBEAT"]
    assert len(STREETBEAT_carts) == 20


def test__write_csv(fs, mocker):
    alternative_line = ["alternative", "mock", "line"]
    alternative_mock = mocker.Mock(
        to_list_for_csv=mocker.Mock(return_value=alternative_line)
    )

    streetbeat_line = ["streetbeat", "abcd", "efgh"]
    streetbeat_mock = mocker.Mock(
        to_list_for_csv=mocker.Mock(return_value=streetbeat_line)
    )

    pro_30_line = ["pro_30", "jklm", "nopq"]
    pro_30_mock = mocker.Mock(
        to_list_for_csv=mocker.Mock(return_value=pro_30_line)
    )

    pro_60_line = ["pro_60", "rstu", "vwxy"]
    pro_60_mock = mocker.Mock(
        to_list_for_csv=mocker.Mock(return_value=pro_60_line)
    )

    statistics_per_group = {
        "ALTERNATIV": alternative_mock,
        "STREETBEAT": streetbeat_mock,
        "PRO_30": pro_30_mock,
        "PRO_60": pro_60_mock
    }

    expected_file_contents = "Group Name,Number of Songs,Shortest Song Length,Longest Song Length,Outlier Limits," \
        "Mean,Standard Deviation,Lower Bound,Number of Songs < Lower Bound,Upper Bound," \
        "Number of Songs > Upper Bound\nalternative,mock,line\npro_30,jklm,nopq\npro_60,rstu,vwxy\n" \
        "streetbeat,abcd,efgh\n"

    root_dir = Path(r"test")
    root_dir.mkdir()

    pathname = root_dir / 'testfile.csv'

    mock_rivendell_carts = "mock_rivendell_carts"

    stats_limits = StatisticsLimits()
    ds = DatabaseStatistics(rivendell_carts=mock_rivendell_carts, output_filename=pathname, stats_limits=stats_limits)

    ds._write_csv(statistics_per_group=statistics_per_group)

    assert pathname.read_text() == expected_file_contents

